/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.contractor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.module.user.entity.User;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code contracts} table.
 *
 * <p>A contract links a {@link Contractor} to a formal service agreement with a
 * defined value, duration, and lifecycle status.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "contracts")
public class Contract {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The contractor party to this contract.
     * Loaded lazily; callers must join-fetch when the contractor name is required.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contractor_id", nullable = false)
    private Contractor contractor;

    /** Short descriptive title for the contract. */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /** Detailed description of the work or service scope. */
    @Column(name = "scope", columnDefinition = "TEXT")
    private String scope;

    /** Total monetary value of the contract. */
    @Column(name = "contract_value", precision = 18, scale = 2)
    private BigDecimal contractValue;

    /** ISO 4217 currency code; defaults to Vietnamese Dong. */
    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "VND";

    /** Date the contract officially commences. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Date the contract expires; {@code null} for open-ended agreements. */
    @Column(name = "end_date")
    private LocalDate endDate;

    /**
     * Current lifecycle status of the contract.
     * Mapped to the PostgreSQL {@code contract_status} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "contract_status")
    private ContractStatus status = ContractStatus.PENDING;

    /** MinIO object key for the signed contract document. {@code null} if not uploaded. */
    @Column(name = "attachment_url", length = 1000)
    private String attachmentUrl;

    /** Free-text notes about the contract. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Staff member who created this contract record.
     * Optional; set to {@code null} if the creating user is later deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "created_by_user_id")
    private User createdBy;

    /**
     * Sent-marker for the expiry notification (G6 once-only fix). {@code null} until
     * the {@code CONTRACT_EXPIRING} dispatch; set in the same transaction as the
     * notification insert so the daily scan never re-notifies the same contract.
     */
    @Column(name = "expiry_notified_at")
    private OffsetDateTime expiryNotifiedAt;

    /** Record creation timestamp. Set once at persist time; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Updates {@code updatedAt} before any JPA merge operation.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
