/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.contractor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.common.audit.CreatableEntity;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity for the {@code contractor_document} table — downloadable DOCUMENT files
 * (pdf/docx/xlsx/pptx/txt) attached to a contractor.
 *
 * <p>Mirrors {@link vn.vtit.gemek.module.announcement.entity.AnnouncementAttachment}: a flat
 * row-per-file list served strictly as forced-download. Append-only (no update path) so it extends
 * {@link CreatableEntity}: the creator actor is captured in {@code created_by} via Spring Data
 * auditing; {@code createdAt} is set by this entity's own {@code @PrePersist}. The {@link #objectKey}
 * follows the convention {@code contractors/{contractorId}/documents/{uuid}} so the staff-only presign
 * gate can parse the owning contractor id from the key alone.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "contractor_document")
public class ContractorDocument extends CreatableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Owning contractor. Lazy — document metadata rarely needs the full parent loaded. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contractor_id", nullable = false)
    private Contractor contractor;

    /** MinIO object key (convention {@code contractors/{contractorId}/documents/{uuid}}). */
    @Column(name = "object_key", nullable = false, columnDefinition = "TEXT")
    private String objectKey;

    /** Detected (Tika magic-byte) content type stored at upload — never the client-supplied header. */
    @Column(name = "content_type", length = 100)
    private String contentType;

    /** Object size in bytes, used for the per-contractor total-size cap. */
    @Column(name = "size_bytes")
    private Long sizeBytes;

    /**
     * Original client filename, shown to staff and used to build the download
     * {@code Content-Disposition} filename (sanitized at presign time). NOT used to build the object key.
     */
    @Column(name = "display_filename", nullable = false, length = 255)
    private String displayFilename;

    /** Row creation timestamp, set once on persist. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Stamps {@link #createdAt} on first persist.
     */
    @PrePersist
    protected void onCreate() {
        // State transition: document row materialised — record its creation instant once.
        this.createdAt = OffsetDateTime.now();
    }
}
