/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.contractor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.user.entity.User;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code contract_payments} table.
 *
 * <p>Records a single payment disbursement made against a {@link Contract}.
 * This is a record-only entity — no disbursement workflow is implemented.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "contract_payments")
public class ContractPayment {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The contract this payment applies to.
     * Loaded lazily; callers must join-fetch when the contract title is required.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contract_id", nullable = false)
    private Contract contract;

    /** Payment amount; must be positive, enforced by the DB CHECK constraint. */
    @Column(name = "amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal amount;

    /** Calendar date on which the payment was made. */
    @Column(name = "payment_date", nullable = false)
    private LocalDate paymentDate;

    /** Optional description of what the payment covers. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** External reference number (bank transfer ID, cheque number, etc.). */
    @Column(name = "reference_number", length = 100)
    private String referenceNumber;

    /**
     * Staff member who recorded this payment.
     * Optional; set to {@code null} if the recording user is later deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "recorded_by_user_id")
    private User recordedBy;

    /** Record creation timestamp. Payments are immutable after creation. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code createdAt} before the first persist.
     * Payments have no {@code updatedAt} because they are append-only records.
     */
    @PrePersist
    public void onPersist() {
        this.createdAt = OffsetDateTime.now();
    }
}
