/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.contractor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code contractors} table.
 *
 * <p>Stub entity for Module 4. Full implementation (contracts, contact history)
 * is added in Module 5.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "contractors")
public class Contractor {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Legal company name. */
    @Column(name = "company_name", nullable = false, length = 255)
    private String companyName;

    /** Primary contact person at the contractor company. */
    @Column(name = "contact_person", length = 255)
    private String contactPerson;

    /** Contact phone number. */
    @Column(name = "phone", length = 20)
    private String phone;

    /** Contact email address. */
    @Column(name = "email", length = 255)
    private String email;

    /** Physical address. */
    @Column(name = "address", columnDefinition = "TEXT")
    private String address;

    /**
     * The contractor's area of specialisation.
     * Mapped to the PostgreSQL {@code contractor_specialty} ENUM via string comparison.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "specialty", nullable = false, columnDefinition = "contractor_specialty")
    private ContractorSpecialty specialty = ContractorSpecialty.OTHER;

    /** Tax identification code. */
    @Column(name = "tax_code", length = 50)
    private String taxCode;

    /**
     * Average rating computed from completed ticket ratings.
     * Recalculated by {@link vn.vtit.gemek.module.contractor.repository.ContractorRepository#recalculateRating}.
     */
    @Column(name = "rating", precision = 3, scale = 2)
    private BigDecimal rating;

    /** Free-text notes about the contractor. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Whether this contractor is available for assignment. */
    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    /** Record creation timestamp. Set once at persist time; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code updated_at} to the current time before any JPA update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
