/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.contractor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code maintenance_schedules} table.
 *
 * <p>Defines a recurring maintenance task linked to a {@link Contract}.
 * The scheduler checks overdue schedules daily and creates notifications in Module 10.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "maintenance_schedules")
public class MaintenanceSchedule {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The contract this schedule belongs to.
     * Loaded lazily; callers must join-fetch when the contract title is required.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contract_id", nullable = false)
    private Contract contract;

    /** Short label for the recurring task (e.g., "Monthly fire extinguisher check"). */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /**
     * How often this task recurs.
     * Mapped to the PostgreSQL {@code schedule_frequency} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "frequency", nullable = false, columnDefinition = "schedule_frequency")
    private ScheduleFrequency frequency;

    /** The next calendar date by which this task must be performed. */
    @Column(name = "next_due_date", nullable = false)
    private LocalDate nextDueDate;

    /** The date the task was last completed; {@code null} if never performed. */
    @Column(name = "last_done_date")
    private LocalDate lastDoneDate;

    /** Optional operational notes or checklist items. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Whether this schedule is currently active and should be checked by the scheduler. */
    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    /** Record creation timestamp. Set once at persist time. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Updates {@code updatedAt} before any JPA merge operation.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
