/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.amenity.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.common.audit.AuditableEntity;

import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code amenities} table.
 *
 * <p>An amenity is a bookable building facility (gym, pool, BBQ area, meeting room, etc.).
 * Active amenities ({@code isActive = true}) are visible to all authenticated users.
 * Deactivation ({@code isActive = false}) is a soft operation that also cancels any pending
 * future bookings — handled in {@code AmenityServiceImpl.deactivateAmenity}.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "amenities")
public class Amenity extends AuditableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Display name of the amenity; must be unique across all amenities. */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /** Optional long-form description of the amenity. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** Physical location within the building (e.g., "Rooftop", "Floor 2"). */
    @Column(name = "location", length = 255)
    private String location;

    /**
     * Maximum simultaneous occupancy.
     * {@code null} means capacity is unconstrained or managed externally.
     */
    @Column(name = "capacity")
    private Short capacity;

    /** Time from which bookings may start each day. */
    @Column(name = "opening_time", nullable = false)
    private LocalTime openingTime;

    /** Time by which all bookings must end each day. */
    @Column(name = "closing_time", nullable = false)
    private LocalTime closingTime;

    /**
     * Maximum number of bookings a single resident may place for this amenity on any given day.
     * Enforced at booking creation time by {@code AmenityServiceImpl}.
     */
    @Column(name = "max_daily_bookings_per_resident", nullable = false)
    private short maxDailyBookingsPerResident;

    /**
     * When {@code true}, bookings start in {@link BookingStatus#PENDING} and require admin approval.
     * When {@code false}, bookings are immediately set to {@link BookingStatus#APPROVED}.
     */
    @Column(name = "requires_approval", nullable = false)
    private boolean requiresApproval;

    /**
     * Whether this amenity is currently accepting bookings.
     * Deactivated amenities ({@code false}) are excluded from the resident-facing list.
     */
    @Column(name = "is_active", nullable = false)
    private boolean active;

    /** Record creation timestamp. Set on first persist; never updated. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt}, {@code updatedAt}, and defaults before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        // Apply DB-matching defaults when fields are not set by the caller.
        if (this.openingTime == null) {
            this.openingTime = LocalTime.of(6, 0);
        }
        if (this.closingTime == null) {
            this.closingTime = LocalTime.of(22, 0);
        }
    }

    /**
     * Updates {@code updatedAt} before any JPA merge operation.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
