/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.amenity.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.common.audit.AuditableEntity;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.resident.entity.Resident;
import vn.vtit.gemek.module.user.entity.User;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code amenity_bookings} table.
 *
 * <p>An amenity booking reserves a time slot at a specific amenity on a given date.
 * Conflict prevention (overlapping slots and daily limit) is enforced in
 * {@code AmenityServiceImpl} using a pessimistic write lock before insertion.
 *
 * <p>Status lifecycle: PENDING → APPROVED/REJECTED/CANCELLED, APPROVED → CANCELLED/COMPLETED.
 * See API-SPEC.md Appendix A for the full transition table.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "amenity_bookings")
public class AmenityBooking extends AuditableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The amenity being booked. Loaded lazily; FK on {@code amenity_id}. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "amenity_id", nullable = false)
    private Amenity amenity;

    /** The resident who created this booking. Loaded lazily; FK on {@code resident_id}. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resident_id", nullable = false)
    private Resident resident;

    /** The apartment the resident belongs to at booking time. FK on {@code apartment_id}. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /** Calendar date for which the amenity is booked. */
    @Column(name = "booking_date", nullable = false)
    private LocalDate bookingDate;

    /** Start time of the reserved slot. Must be within amenity opening hours. */
    @Column(name = "start_time", nullable = false)
    private LocalTime startTime;

    /** End time of the reserved slot. Must be within amenity closing hours and after startTime. */
    @Column(name = "end_time", nullable = false)
    private LocalTime endTime;

    /**
     * Current lifecycle status of this booking.
     * Mapped to the PostgreSQL {@code booking_status} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "booking_status")
    private BookingStatus status;

    /** Optional free-text notes provided by the resident at booking time. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Reason provided by the admin when rejecting the booking.
     * Only meaningful when {@code status = REJECTED}.
     */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;

    /**
     * The admin user who approved or rejected this booking.
     * {@code null} for auto-approved bookings or bookings that were never manually reviewed.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "approved_by_user_id")
    private User approvedBy;

    /**
     * Timestamp at which the booking was approved or rejected by an admin.
     * {@code null} for auto-approved bookings until a manual action is taken.
     */
    @Column(name = "approved_at")
    private OffsetDateTime approvedAt;

    /** Record creation timestamp. Set on first persist; never updated. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Updates {@code updatedAt} before any JPA merge operation.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
