/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.vehicle.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.resident.entity.Resident;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code vehicles} table.
 *
 * <p>A vehicle record belongs to a resident and is associated with an apartment.
 * Soft deletion is used: setting {@code isActive} to {@code false} deactivates the
 * registration without removing the historical record.
 * License plates are globally unique across all vehicle records.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "vehicles")
public class Vehicle {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The resident who registered this vehicle. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resident_id", nullable = false)
    private Resident resident;

    /** The apartment this vehicle is associated with. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /**
     * Vehicle type (CAR, MOTORBIKE, BICYCLE, OTHER).
     * Mapped to the PostgreSQL {@code vehicle_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, columnDefinition = "vehicle_type")
    private VehicleType type;

    /** Vehicle license plate number. Must be globally unique across all vehicle records. */
    @Column(name = "license_plate", nullable = false, length = 20, unique = true)
    private String licensePlate;

    /** Optional vehicle brand (e.g., Toyota). */
    @Column(name = "brand", length = 100)
    private String brand;

    /** Optional vehicle model (e.g., Camry). */
    @Column(name = "model", length = 100)
    private String model;

    /** Optional vehicle colour. */
    @Column(name = "color", length = 50)
    private String color;

    /** Optional notes. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Whether this vehicle registration is active.
     * Set to {@code false} on soft deletion; never physically deleted.
     */
    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    /** Record creation timestamp. Set by PostgreSQL default; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by the service layer on every write. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
