-- =============================================================================
-- V2: Admin seed (placeholder — seeding now handled by AdminSeeder on startup)
-- Version: 2.0
-- Date: 2026-06-04
-- =============================================================================
-- Admin user is created by AdminSeeder (vn.vtit.gemek.config.AdminSeeder)
-- on first application startup when ADMIN_EMAIL and ADMIN_PASSWORD are set.
-- Flyway placeholder seeding was removed to avoid Docker Compose $-interpolation
-- corrupting BCrypt hashes passed via env_file.
-- =============================================================================
