/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.resident.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.user.entity.User;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code residents} table.
 *
 * <p>Stub entity created in Module 2 to satisfy the apartment detail query.
 * Fully implemented in Module 3 (Residents and Vehicles).
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "residents")
public class Resident {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The user account linked to this resident record. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The apartment this resident is assigned to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /**
     * Resident type — OWNER or TENANT.
     * Mapped to the PostgreSQL {@code resident_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, columnDefinition = "resident_type")
    private ResidentType type;

    /** Date the resident moved in. */
    @Column(name = "move_in_date", nullable = false)
    private LocalDate moveInDate;

    /** Date the resident moved out. {@code null} means currently active. */
    @Column(name = "move_out_date")
    private LocalDate moveOutDate;

    /** Whether this resident is the primary contact for the apartment. */
    @Column(name = "is_primary_contact", nullable = false)
    private boolean primaryContact = false;

    /** Optional free-text notes. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Record creation timestamp. Set by PostgreSQL default; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
