/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.resident.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.common.audit.CreatableEntity;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.user.entity.User;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code resident_history} audit table.
 *
 * <p>An immutable log entry is appended whenever a resident is moved in, moved out,
 * changes type, or is designated as the primary contact for an apartment.
 * Supported event values: MOVED_IN, MOVED_OUT, TYPE_CHANGED, PRIMARY_CONTACT_SET.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "resident_history")
public class ResidentHistory extends CreatableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The apartment this history entry belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /** The resident user this history entry belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Resident type at the time the event occurred.
     * Mapped to the PostgreSQL {@code resident_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "type", nullable = false, columnDefinition = "resident_type")
    private ResidentType type;

    /**
     * The event that triggered this history entry.
     * Valid values: MOVED_IN, MOVED_OUT, TYPE_CHANGED, PRIMARY_CONTACT_SET.
     */
    @Column(name = "event", nullable = false, length = 50)
    private String event;

    /** The date on which the event occurred. */
    @Column(name = "event_date", nullable = false)
    private LocalDate eventDate;

    /**
     * The staff member or admin who performed the change.
     * May be {@code null} if the change was system-initiated.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "changed_by_user_id")
    private User changedBy;

    /** Optional free-text notes recorded at the time of the event. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Record creation timestamp. Set by PostgreSQL default; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code created_at} and {@code updated_at} on initial persist.
     */
    @PrePersist
    public void onCreate() {
        this.createdAt = OffsetDateTime.now();
    }
}
