/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.apartment.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code apartments} table.
 *
 * <p>Each apartment belongs to a {@link Block} and is identified by its unit number
 * within that block. The {@code status} column maps to the PostgreSQL
 * {@code apartment_status} ENUM type.
 *
 * <p>Resident and vehicle collections are intentionally omitted to avoid N+1 queries.
 * The service layer fetches them separately via dedicated repository queries when
 * building the detail response.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "apartments")
public class Apartment {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The block this apartment belongs to.
     * Fetched eagerly because every apartment response includes the block name.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "block_id", nullable = false)
    private Block block;

    /** Floor number within the block. Must be zero or positive. */
    @Column(name = "floor", nullable = false)
    private Short floor;

    /** Unit number unique within the block (e.g., "A301"). */
    @Column(name = "unit_number", nullable = false, length = 20)
    private String unitNumber;

    /** Floor area in square metres. Null if unknown. */
    @Column(name = "area_sqm", precision = 8, scale = 2)
    private BigDecimal areaSqm;

    /**
     * Current occupancy status of the apartment.
     * Mapped to the PostgreSQL {@code apartment_status} ENUM via string comparison.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, columnDefinition = "apartment_status")
    private ApartmentStatus status = ApartmentStatus.AVAILABLE;

    /** Optional free-text notes about this apartment. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Record creation timestamp. Set by PostgreSQL default; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code updated_at} to the current time before any JPA update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
