/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.user.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.common.audit.AuditableEntity;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code users} table.
 *
 * <p>Central identity record for all roles in the system.
 * The {@code role} column maps to the PostgreSQL {@code user_role} ENUM type.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "users")
public class User extends AuditableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Informational email address. Nullable; unique when provided (V12 migration). */
    @Column(name = "email", nullable = true, unique = true, length = 255)
    private String email;

    /** Canonical phone number used as the primary login identifier. NOT NULL, UNIQUE (V12 migration). */
    @Column(name = "phone", nullable = false, unique = true, length = 20)
    private String phone;

    /** Display name. */
    @Column(name = "full_name", nullable = false, length = 255)
    private String fullName;

    /** BCrypt-hashed password. Never returned in API responses. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * User's role in the system.
     * Mapped to the PostgreSQL {@code user_role} ENUM via string comparison.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "role", nullable = false, columnDefinition = "user_role")
    private UserRole role;

    /** Firebase Cloud Messaging device token for push notifications. */
    @Column(name = "fcm_token", length = 500)
    private String fcmToken;

    /** Whether the account is active. Deactivated accounts cannot log in. */
    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    /** MinIO object key for the user's avatar. Not a full URL. */
    @Column(name = "avatar_url", length = 1000)
    private String avatarUrl;

    /** Date of birth. Nullable — not required at account creation. */
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    /** Timestamp of the user's most recent successful login. */
    @Column(name = "last_login_at")
    private OffsetDateTime lastLoginAt;

    /** Record creation timestamp. Set by PostgreSQL default; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code created_at} and {@code updated_at} on initial persist.
     */
    @PrePersist
    public void onCreate() {
        this.createdAt = OffsetDateTime.now();
        this.updatedAt = OffsetDateTime.now();
    }

    /**
     * Sets {@code updated_at} to the current time before any JPA update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
