/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.parking.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code guest_vehicles} table.
 *
 * <p>Records a visitor vehicle entry event. {@code exitTime} is {@code null} while the
 * guest vehicle is still on the premises; it is populated via the checkout endpoint.
 * This entity is append-only — there is no {@code updatedAt} column.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "guest_vehicles")
public class GuestVehicle {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** License plate of the visiting vehicle. */
    @Column(name = "license_plate", nullable = false, length = 20)
    private String licensePlate;

    /** Name of the vehicle owner or driver. May be {@code null}. */
    @Column(name = "owner_name", length = 255)
    private String ownerName;

    /** The apartment being visited. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "host_apartment_id", nullable = false)
    private Apartment hostApartment;

    /** Timestamp when the guest vehicle entered the premises. */
    @Column(name = "entry_time", nullable = false)
    private OffsetDateTime entryTime;

    /**
     * Timestamp when the guest vehicle exited the premises.
     * {@code null} while the vehicle is still present.
     */
    @Column(name = "exit_time")
    private OffsetDateTime exitTime;

    /** Optional purpose of the visit (e.g., "Delivery", "Visiting resident"). */
    @Column(name = "purpose", length = 255)
    private String purpose;

    /**
     * Staff member who logged this entry. May be {@code null} if the recording user
     * has since been deleted (FK ON DELETE SET NULL).
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "recorded_by_user_id")
    private User recordedBy;

    /** Optional free-text notes about the visit. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code createdAt} and defaults {@code entryTime} to now before the first INSERT.
     * {@code entryTime} is also defaulted here so callers that do not supply it get a
     * sensible value; the request DTO may override it explicitly.
     */
    @PrePersist
    void onPrePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        if (this.entryTime == null) {
            this.entryTime = now;
        }
    }
}
