/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.parking.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.vehicle.entity.Vehicle;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code parking_assignments} table.
 *
 * <p>Links a {@link ParkingSlot} to a {@link Vehicle} and {@link Apartment} for a date range.
 * An assignment with a {@code null} {@code endDate} is considered active; the slot's
 * {@code status} is set to {@code OCCUPIED} when this record is created and back to
 * {@code AVAILABLE} when {@code endDate} is populated.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "parking_assignments")
public class ParkingAssignment {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The parking slot being assigned. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parking_slot_id", nullable = false)
    private ParkingSlot parkingSlot;

    /** The vehicle assigned to the slot. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vehicle_id", nullable = false)
    private Vehicle vehicle;

    /** The apartment whose resident is using this slot. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /** Date from which the assignment is effective. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /**
     * Date on which the assignment ends.
     * {@code null} indicates the assignment is currently active.
     */
    @Column(name = "end_date")
    private LocalDate endDate;

    /** Optional parking card or access tag number issued for this assignment. */
    @Column(name = "parking_card_number", length = 50)
    private String parkingCardNumber;

    /** Optional free-text notes about this assignment. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Timestamp of the most recent update. Refreshed by {@link #onPreUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first INSERT.
     */
    @PrePersist
    void onPrePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Refreshes {@code updatedAt} before every UPDATE.
     */
    @PreUpdate
    void onPreUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
