/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.parking.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code parking_slots} table.
 *
 * <p>Each slot has a unique slot number and is categorised by type (CAR, MOTORBIKE, BICYCLE).
 * The {@code status} field reflects current occupancy and is updated atomically
 * alongside the corresponding {@link ParkingAssignment} record.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "parking_slots")
public class ParkingSlot {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Human-readable slot identifier (e.g., "B1-001").
     * Must be unique across all parking slots.
     */
    @Column(name = "slot_number", nullable = false, length = 20, unique = true)
    private String slotNumber;

    /** Optional zone or level label (e.g., "B1", "Level 2"). */
    @Column(name = "zone", length = 50)
    private String zone;

    /**
     * Physical vehicle type this slot accommodates.
     * Maps to the PostgreSQL {@code parking_slot_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "type", nullable = false, columnDefinition = "parking_slot_type")
    private ParkingSlotType type;

    /**
     * Current occupancy status of the slot.
     * Maps to the PostgreSQL {@code parking_slot_status} ENUM.
     * Updated atomically when an assignment is created or ended.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "parking_slot_status")
    private ParkingSlotStatus status = ParkingSlotStatus.AVAILABLE;

    /** Optional free-text notes about this slot. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Timestamp of the most recent update. Refreshed by {@link #onPreUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first INSERT.
     */
    @PrePersist
    void onPrePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Refreshes {@code updatedAt} before every UPDATE.
     */
    @PreUpdate
    void onPreUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
