/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.announcement.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code announcement_reads} table.
 *
 * <p>Records that a specific user has read a specific announcement.
 * The unique constraint {@code uq_ar_unique (announcement_id, user_id)} ensures
 * only one read record per user per announcement, making mark-read idempotent.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "announcement_reads")
public class AnnouncementRead {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The announcement that was read. Cascade delete removes this record when the announcement is deleted. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "announcement_id", nullable = false)
    private Announcement announcement;

    /** The user who read the announcement. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Timestamp at which the user marked the announcement as read. Set on first persist. */
    @Column(name = "read_at", nullable = false, updatable = false)
    private OffsetDateTime readAt;

    /**
     * Sets {@code readAt} to the current time before the first persist.
     */
    @PrePersist
    public void onPersist() {
        this.readAt = OffsetDateTime.now();
    }
}
