/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.announcement.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.apartment.entity.Block;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code announcements} table.
 *
 * <p>An announcement is created as a draft ({@code publishedAt} is {@code null}) and
 * becomes visible to residents only after it is explicitly published via the publish endpoint.
 * Scope targeting is enforced at both the service layer and via a DB-level CHECK constraint.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "announcements")
public class Announcement {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Short headline for the announcement. */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /** Full body text of the announcement. */
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Content category of the announcement.
     * Mapped to the PostgreSQL {@code announcement_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, columnDefinition = "announcement_type")
    private AnnouncementType type;

    /**
     * Delivery scope of the announcement.
     * Mapped to the PostgreSQL {@code announcement_scope} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "scope", nullable = false, columnDefinition = "announcement_scope")
    private AnnouncementScope scope;

    /**
     * Target block for BLOCK or FLOOR scoped announcements.
     * {@code null} when {@code scope} is {@link AnnouncementScope#ALL}.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "target_block_id")
    private Block targetBlock;

    /**
     * Target floor number for FLOOR scoped announcements.
     * {@code null} when {@code scope} is {@link AnnouncementScope#ALL} or {@link AnnouncementScope#BLOCK}.
     */
    @Column(name = "target_floor")
    private Short targetFloor;

    /** Whether to deliver this announcement via Firebase push notification. */
    @Column(name = "send_push", nullable = false)
    private boolean sendPush = true;

    /** Whether to deliver this announcement via email. */
    @Column(name = "send_email", nullable = false)
    private boolean sendEmail = false;

    /** Whether to deliver this announcement via SMS. */
    @Column(name = "send_sms", nullable = false)
    private boolean sendSms = false;

    /**
     * The admin user who created this announcement.
     * May be {@code null} if the creator account was later deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "created_by_user_id")
    private User createdBy;

    /**
     * Timestamp at which the announcement was published and became visible to residents.
     * {@code null} means the announcement is still a draft.
     */
    @Column(name = "published_at")
    private OffsetDateTime publishedAt;

    /** Record creation timestamp. Set on first persist; never updated. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code updatedAt} to the current time before any JPA update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
