/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.common.audit.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

/**
 * JPA entity representing the {@code audit_logs} table.
 *
 * <p>Provides an immutable record of every state-changing operation in the system.
 * Rows are written fire-and-forget by {@link vn.vtit.gemek.common.audit.AuditLogAspect}
 * so that audit failures never roll back the primary transaction.
 *
 * <p>JSONB columns ({@code old_value}, {@code new_value}) are stored as {@link String}
 * because the application serialises the values to JSON before persisting.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "audit_logs")
public class AuditLog {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The user who performed the action.
     * Nullable — {@code null} indicates a system-initiated action (e.g., scheduler).
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "user_id")
    private User user;

    /** Label for the operation performed (e.g., "CREATE", "UPDATE", "DELETE"). */
    @Column(name = "action", nullable = false, length = 100)
    private String action;

    /** Simple class or domain name of the affected entity (e.g., "Contract", "Ticket"). */
    @Column(name = "entity_type", nullable = false, length = 100)
    private String entityType;

    /** UUID of the affected entity record. May be {@code null} for bulk or non-entity operations. */
    @Column(name = "entity_id")
    private UUID entityId;

    /**
     * JSON snapshot of the entity state before the operation.
     * Stored in the PostgreSQL {@code jsonb} column type.
     */
    @Column(name = "old_value", columnDefinition = "jsonb")
    private String oldValue;

    /**
     * JSON snapshot of the entity state after the operation.
     * Stored in the PostgreSQL {@code jsonb} column type.
     */
    @Column(name = "new_value", columnDefinition = "jsonb")
    private String newValue;

    /** IP address of the client that made the request; may be {@code null} for scheduler actions. */
    @Column(name = "ip_address", length = 45)
    private String ipAddress;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code createdAt} to UTC now before the first INSERT if not already set.
     */
    @PrePersist
    void onPrePersist() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now(ZoneOffset.UTC);
        }
    }
}
