/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.notification.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

/**
 * JPA entity representing the {@code notification_subscriptions} table (V14).
 *
 * <p>One row = one user's membership in the notification thread of one entity.
 * The entity reference is polymorphic ({@code entityType} + {@code entityId},
 * no foreign key by design) so the same table serves tickets now and comments
 * or other entities later (N4). Rows are immutable after creation.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "notification_subscriptions")
public class NotificationSubscription {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The subscribed user. Loaded lazily; callers must join-fetch when user
     * fields are required.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Entity-type label, same label space as {@code notifications.reference_type}
     * (e.g. "Ticket").
     */
    @Column(name = "entity_type", nullable = false, length = 100)
    private String entityType;

    /** UUID of the subscribed entity; interpreted together with {@link #entityType}. */
    @Column(name = "entity_id", nullable = false)
    private UUID entityId;

    /** How the user joined the thread. */
    @Enumerated(EnumType.STRING)
    @Column(name = "joined_via", nullable = false, length = 20)
    private SubscriptionJoinedVia joinedVia;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code createdAt} to UTC now before the first INSERT if not already set.
     */
    @PrePersist
    void onPrePersist() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now(ZoneOffset.UTC);
        }
    }
}
