/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.notification.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.common.audit.CreatableEntity;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

/**
 * JPA entity representing the {@code notifications} table.
 *
 * <p>Stores in-app notification records addressed to a specific user.
 * Records are immutable after creation; the only mutable field is {@code isRead}.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "notifications")
public class Notification extends CreatableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The user this notification is addressed to.
     * Loaded lazily; callers must join-fetch when user fields are required.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Short subject line shown in the notification list. */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /** Optional full notification body text. */
    @Column(name = "body", columnDefinition = "TEXT")
    private String body;

    /**
     * The category of event that triggered this notification.
     * Maps to the PostgreSQL {@code notification_type} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "type", nullable = false, columnDefinition = "notification_type")
    private NotificationType type;

    /**
     * Optional UUID of the entity this notification relates to.
     * Interpreted together with {@link #referenceType}.
     */
    @Column(name = "reference_id")
    private UUID referenceId;

    /**
     * Optional entity-type label paired with {@link #referenceId}
     * (e.g., "Contract", "MaintenanceSchedule").
     */
    @Column(name = "reference_type", length = 100)
    private String referenceType;

    /** Whether the user has marked this notification as read. */
    @Column(name = "is_read", nullable = false)
    private boolean isRead = false;

    /** Timestamp when this record was first persisted. Set once by {@link #onPrePersist()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Sets {@code createdAt} to UTC now before the first INSERT if not already set.
     */
    @PrePersist
    void onPrePersist() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now(ZoneOffset.UTC);
        }
    }
}
