/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.ticket.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code ticket_status_history} table.
 *
 * <p>Append-only audit log of every status transition on a ticket.
 * Records are never updated after creation — there is no {@code @PreUpdate} hook.
 * Cascade-deleted when the parent ticket is deleted.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "ticket_status_history")
public class TicketStatusHistory {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The ticket whose status changed. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ticket_id", nullable = false)
    private Ticket ticket;

    /**
     * The status before the transition. Null on the initial NEW entry when the ticket is first created.
     * Mapped to the PostgreSQL {@code ticket_status} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "old_status", columnDefinition = "ticket_status")
    private TicketStatus oldStatus;

    /**
     * The status after the transition.
     * Mapped to the PostgreSQL {@code ticket_status} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "new_status", nullable = false, columnDefinition = "ticket_status")
    private TicketStatus newStatus;

    /** User who triggered the transition. Nullable — set to NULL if the user is later deleted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "changed_by_user_id")
    private User changedBy;

    /** Optional notes explaining the reason for the transition. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Timestamp when this history record was created. Set once at persist time. */
    @Column(name = "changed_at", nullable = false, updatable = false)
    private OffsetDateTime changedAt;

    /**
     * Sets {@code changedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        this.changedAt = OffsetDateTime.now();
    }
}
