/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.ticket.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.common.audit.AuditableEntity;
import vn.vtit.gemek.module.apartment.entity.Apartment;
import vn.vtit.gemek.module.contractor.entity.Contractor;
import vn.vtit.gemek.module.user.entity.User;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code tickets} table.
 *
 * <p>A ticket captures any resident request — maintenance, complaint, administrative
 * query, or suggestion. The {@code category} field drives SLA assignment and
 * contractor routing rules enforced at both the DB (CHECK constraint) and service layer.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "tickets")
public class Ticket extends AuditableEntity {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The apartment this ticket was submitted for.
     * Fetched lazily — loaded explicitly when needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "apartment_id", nullable = false)
    private Apartment apartment;

    /**
     * The user who submitted this ticket.
     * Fetched lazily.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "submitted_by_user_id", nullable = false)
    private User submittedBy;

    /**
     * Category of the request. Determines SLA and contractor-assignment eligibility.
     * Mapped to the PostgreSQL {@code ticket_category} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "category", nullable = false, columnDefinition = "ticket_category")
    private TicketCategory category;

    /** Short title describing the request. Maximum 255 characters. */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /** Optional detailed description of the issue. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Current lifecycle status of the ticket.
     * Mapped to the PostgreSQL {@code ticket_status} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "ticket_status")
    private TicketStatus status = TicketStatus.NEW;

    /**
     * Priority level. Defaults to MEDIUM.
     * Mapped to the PostgreSQL {@code ticket_priority} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "priority", nullable = false, columnDefinition = "ticket_priority")
    private TicketPriority priority = TicketPriority.MEDIUM;

    /**
     * Staff member assigned to handle this ticket.
     * Mutually exclusive with {@link #assignedToContractor}.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "assigned_to_user_id")
    private User assignedToUser;

    /**
     * External contractor assigned to handle this ticket.
     * Only permitted when {@link #category} is {@link TicketCategory#MAINTENANCE_REPAIR}.
     * Mutually exclusive with {@link #assignedToUser}.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "assigned_to_contractor_id")
    private Contractor assignedToContractor;

    /** Planned date on which work is scheduled to begin or complete. */
    @Column(name = "scheduled_date")
    private LocalDate scheduledDate;

    /** Timestamp when the ticket was marked DONE. Null until resolved. */
    @Column(name = "completed_date")
    private OffsetDateTime completedDate;

    /** Resident-provided rating (1–5) after ticket is DONE. Null until rated. */
    @Column(name = "rating")
    private Short rating;

    /** Optional comment accompanying the resident's rating. */
    @Column(name = "rating_comment", columnDefinition = "TEXT")
    private String ratingComment;

    /**
     * SLA deadline computed at creation time as {@code createdAt + category.slaHours}.
     * Null for SUGGESTION_FEEDBACK tickets which carry no SLA obligation.
     */
    @Column(name = "sla_deadline")
    private OffsetDateTime slaDeadline;

    /** Staff-provided notes explaining the resolution. */
    @Column(name = "resolution_notes", columnDefinition = "TEXT")
    private String resolutionNotes;

    /**
     * Sent-marker for the SLA warning notification (N3 P6). {@code null} until the
     * {@code TICKET_SLA_WARNING} dispatch; set in the same transaction as the
     * notification insert so a re-scan can never re-notify. Also set without a
     * warning row when the ticket is first seen already overdue. If a future
     * feature ever edits {@link #slaDeadline}, it must null both markers.
     */
    @Column(name = "sla_warning_notified_at")
    private OffsetDateTime slaWarningNotifiedAt;

    /**
     * Sent-marker for the SLA breach notification (N3 P6). {@code null} until the
     * {@code TICKET_SLA_BREACHED} dispatch; same-transaction rule as the warning marker.
     */
    @Column(name = "sla_overdue_notified_at")
    private OffsetDateTime slaOverdueNotifiedAt;

    /**
     * Creator-chosen community visibility flag. Immutable after create (G3) —
     * no service path mutates it post-persist. Public tickets are readable by
     * all residents in redacted form; photos stay household/staff-only (F-05 gate).
     */
    @Column(name = "is_public", nullable = false)
    private boolean isPublic = false;

    /** Record creation timestamp. Set at persist time; never updated by JPA. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Record last-modified timestamp. Updated by {@link #onUpdate()}. */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Sets {@code createdAt} and {@code updatedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code updatedAt} to the current time before any JPA update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
