/*
 * Copyright (c) 2026 VTIT — Gemek Premium Apartment Management System.
 * All rights reserved.
 */
package vn.vtit.gemek.module.ticket.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import vn.vtit.gemek.module.user.entity.User;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing the {@code ticket_photos} table.
 *
 * <p>Photos are stored in MinIO. Only the object key is persisted here.
 * Presigned URLs are generated on demand by {@link vn.vtit.gemek.common.storage.FileStorageService}.
 * Records are deleted via {@code ON DELETE CASCADE} when their parent ticket is deleted.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "ticket_photos")
public class TicketPhoto {

    /** Unique identifier — UUID generated by PostgreSQL {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The ticket this photo documents. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ticket_id", nullable = false)
    private Ticket ticket;

    /** MinIO object key for the stored file. Not a full URL. */
    @Column(name = "file_url", nullable = false, length = 1000)
    private String fileUrl;

    /** Original file name as provided by the uploader. */
    @Column(name = "file_name", length = 255)
    private String fileName;

    /** MIME type of the uploaded file (e.g. {@code image/jpeg}). */
    @Column(name = "mime_type", length = 100)
    private String mimeType;

    /** File size in bytes. */
    @Column(name = "file_size")
    private Integer fileSize;

    /**
     * Phase of ticket work when the photo was taken.
     * Mapped to the PostgreSQL {@code photo_phase} ENUM.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "phase", nullable = false, columnDefinition = "photo_phase")
    private PhotoPhase phase = PhotoPhase.BEFORE;

    /** User who uploaded the photo. Nullable — set to NULL if the user is later deleted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "uploaded_by")
    private User uploadedBy;

    /** Timestamp when the photo was uploaded. Set once at persist time. */
    @Column(name = "uploaded_at", nullable = false, updatable = false)
    private OffsetDateTime uploadedAt;

    /**
     * Sets {@code uploadedAt} before the first persist.
     */
    @PrePersist
    public void onPersist() {
        this.uploadedAt = OffsetDateTime.now();
    }
}
